apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: petite-blackbird-go 
  janus-idp.io/tekton: petite-blackbird-go
  backstage.io/kubernetes-id: petite-blackbird-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: petite-blackbird-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  