apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: petite-blackbird-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: petite-blackbird-go 
  name: petite-blackbird-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: petite-blackbird-go 
